import type { NextPage } from 'next'
import Head from 'next/head'
import Menu from '../../components/menu'

const Chronology: NextPage = () => {
  return (
    <>
      <Head>
        <title>Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Menu></Menu>

    </>
  )
}

export default Chronology
