import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MainMenu from '../components/mainmenu'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <MainMenu></MainMenu>

      <div className={styles.submenu}></div>

      <main className={styles.main}>

      </main>

    </div>
  )
}

export default Home
