export interface ICUParams {
  library: never;
  contents: never;
  wiki: never;
  chronicles: never;
  library_short_description: never;
  contents_short_description: never;
  wiki_short_description: never;
  chronicles_short_description: never;
  news: never;
  gallery: never;
  archives: never;
  about_us: never;
  licensing_notice: never;
  copyright_notice: never;
  contents_description: never;
  type: { count: number };
  category: { count: number };
  size: never;
  release_date: never;
  release_year: never;
  details: never;
  price: never;
  width: never;
  height: never;
  thickness: never;
  subitem: { count: number };
  variant: { count: number };
  summary: never;
  audio: never;
  video: never;
  textual: never;
  game: never;
  other: never;
  left_to_right: never;
  right_to_left: never;
  page: { count: number };
  page_order: never;
  binding: never;
  type_information: never;
  front_matter: never;
  back_matter: never;
  open_content: never;
  read_content: never;
  watch_content: never;
  listen_content: never;
  view_scans: never;
  paperback: never;
  hardcover: never;
  select_language: never;
  language: { count: number };
  library_description: never;
  wiki_description: never;
  chronicles_description: never;
  news_description: never;
  archives_description: never;
  about_us_description: never;
  page_not_found: never;
  default_description: never;
  name: never;
  show_subitems: never;
  show_primary_items: never;
  show_secondary_items: never;
  order_by: never;
  group_by: never;
  select_option_sidebar: never;
  group: never;
  settings: never;
  theme: never;
  light: never;
  auto: never;
  dark: never;
  font_size: never;
  player_name: never;
  currency: never;
  font: never;
  calculated: never;
  status_incomplete: never;
  status_draft: never;
  status_review: never;
  status_done: never;
  incomplete: never;
  draft: never;
  review: never;
  done: never;
  status: never;
  transcribers: never;
  translators: never;
  proofreaders: never;
  transcript_notice: never;
  translation_notice: never;
  source_language: never;
  pronouns: never;
  item: { count: number };
  content: never;
  open_settings: never;
  change_language: never;
  open_search: never;
  chronology: never;
  accords_handbook: never;
  legality: never;
  sharing_policy: never;
  contact_us: never;
  email: never;
  email_gdpr_notice: never;
  message: never;
  send: never;
  response_invalid_code: never;
  response_invalid_email: never;
  response_email_success: never;
  always_show_info: never;
  item_not_available: never;
  primary_language: never;
  secondary_language: never;
  combine_related_contents: never;
  previous_content: { count: number };
  followup_content: { count: number };
  videos: never;
  view_on: never;
  channel: never;
  subscribers: never;
  description: never;
  available_at: never;
  search_title: never;
  want_it: never;
  have_it: never;
  source: never;
  reset_all_filters: never;
  only_display_items_i_have: never;
  only_display_items_i_want: never;
  only_display_unmarked_items: never;
  display_all_items: never;
  table_of_contents: never;
  no_results_message: never;
  all: never;
  special_pages: never;
  scan: never;
  scanlation: never;
  scanners: never;
  cleaners: never;
  typesetters: never;
  notes: never;
  cover: never;
  tags: never;
  no_source_warning: never;
  copy_anchor_link: never;
  anchor_link_copied: never;
  folders: never;
  empty_folder_message: never;
  switch_to_grid_view: never;
  switch_to_folder_view: never;
  content_is_not_available: never;
  paper_texture: never;
  book_fold: never;
  lighting: never;
  side_pages: never;
  shadow: never;
  night_reader: never;
  single_page_view: never;
  double_page_view: never;
  reset_all_options: never;
  reading_layout: never;
  quality: never;
  only_unavailable_videos: never;
  oldest: never;
  newest: never;
  least_popular: never;
  most_popular: never;
  shortest: never;
  longest: never;
  search: never;
  showing_x_out_of_y_results: {
    x: Date | boolean | number | string;
    y: Date | boolean | number | string;
  };
  return_to_x: { x: undefined | null | Date | boolean | number | string };
  x_results: { x: number };
  definition_x: { x: Date | boolean | number | string };
  subitem_of_x: { x: Date | boolean | number | string };
  variant_of_x: { x: Date | boolean | number | string };
  dark_mode_extension_warning: never;
  weapon: { count: number };
  weapons_description: never;
  level_x: { x: Date | boolean | number | string };
  story_x: { x: Date | boolean | number | string };
  player_name_tooltip: never;
  download_scans: never;
}
